language: python
jobs:
  include:
    - if: type = pull_request
      script:
        - echo "Validate Pull Request"

    - if: type = push AND NOT branch = master
      script:
        - echo "Ordinary push"

    - if: type = push AND branch = master
      install:
        - pip install -r requirements.txt
      script:
        - python travis.py
      before_install:
        - openssl aes-256-cbc -K $encrypted_2c6bf604352c_key -iv $encrypted_2c6bf604352c_iv -in serviceAccount.json.enc -out serviceAccount.json -d